
tasks:
  - init: echo 'init script' # runs during prebuild
    command: echo 'start script'

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - robole.javascript-snippets
    - https://github.com/cloudybasement/vue-training/raw/1f7df9a8eca33a7bb4e0b6d54eeb90e0a1e0f220/.vscode/sdras.vue-vscode-snippets-3.1.1.vsix
    - ecmel.vscode-html-css
    - https://github.com/cloudybasement/vue-training/raw/1f7df9a8eca33a7bb4e0b6d54eeb90e0a1e0f220/.vscode/Vue.volar-0.38.5@linux-x64.vsix
